spring.application.name=Product-Service

#server.port=9091
spring.boot.admin.client.url = http://localhost:1111
#management.endpoint.web.exposure.include=*



eureka.instance.prefer-ip-address=true






# 1. THE GATEKEEPER: This opens all doors for the Admin Server
management.endpoints.web.exposure.include=*

# 2. THE INSIGHTS: Enables detailed health and info tabs
management.endpoint.health.show-details=always
management.info.env.enabled=true

# 3. THE LOGGERS & CACHES: Explicitly enable these specific features
management.endpoint.loggers.enabled=true
management.endpoint.caches.enabled=true
management.endpoint.threaddump.enabled=true

# 4. THE ENVIRONMENT: Required to see "Environment" and "Config Properties" values
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always

# 5. THE MAPPINGS: Allows you to see all your @RequestMapping paths
management.endpoint.mappings.enabled=true
